@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

object ip_homeIP
ip_homeIP : address = "192.168.0.3" 
ip_homeIP : version = "v4" 

hide ip members
hide ip_home members

"ip" --> ip_homeIP
"ip_home" --> ip_homeIP
@enduml
