@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

object Strin1
Strin1 : l = "m ipsum" 

object Numbe1
Numbe1 : l = 10 

hide variable members
hide variable_temp members

"variable" --> Numbe1
"variable_temp" --> Strin1
@enduml
