@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

class ComicsUtil {
  {static} namesByComics(characters: Array, comics: String): Array
  {static} weightAvg(characters: Array, comics: String): Number
  {static} heightAvg(characters: Array, comics: String): Number
}
@enduml
